quarkus:
  datasource:
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5431/smartbar-backoffice
  hibernate-orm:
    database:
      generation: drop-and-create

