quarkus:
  datasource:
    username: postgres
    password: postgres
    jdbc: # blocking
      url: jdbc:postgresql://localhost:6000/smartbar-backoffice

  hibernate-orm:
    database:
      generation: drop-and-create