### Get all
GET {{url}}/tables

### Get single
GET {{url}}/tables/3000


### Create new
POST  http://0.0.0.0:9000/tables
Content-Type: application/json

{
  "name": "Berlin",
  "seatCount": 3,
  "active": false
}

### Modify
PUT {{url}}/tables/1
Content-Type: application/json

{
  "name": "costa-rica",
  "seatCount": 10,
  "active": true
}

### Delete
DELETE {{url}}/tables/1